### PR TITLE
Upgrade cargo crate to 0.73.1

### LINKED ISSUE #479: Panic on `assertion failed: self.pending_ids.insert(id)`
Ran in the root directory for [Gex](https://github.com/Piturnah/gex), panicked:

```console
$ cargo geiger
thread 'main' panicked at 'assertion failed: self.pending_ids.insert(id)', /home/pit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-0.69.1/src/cargo/core/package.rs:708:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details>
<summary>
Backtrace
</summary>

```console
thread 'main' panicked at 'assertion failed: self.pending_ids.insert(id)', /home/pit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-0.69.1/src/cargo/core/package.rs:708:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: cargo::core::package::Downloads::start
   4: cargo::core::package::PackageSet::get_many
   5: cargo::ops::cargo_clean::clean
   6: cargo_geiger::scan::rs_file::resolve_rs_file_deps
   7: cargo_geiger::scan::default::scan
   8: cargo_geiger::scan::default::table::scan_to_table
   9: cargo_geiger::scan::default::scan_unsafe
  10: cargo_geiger::scan::scan
  11: cargo_geiger::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

## Environment
```console
$ cargo-geiger --version
cargo-geiger 0.11.6

$ cargo --version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
```
OS: NixOS 23.05

### PR DESCRIPTION
**Pull request by fintelia**
Seems to fix #479

### CODE REVIEW

**Comment by klimburg** [comment]
For what its worth this didn't fix things for me 

```
$ cargo install cargo-geiger --git https://github.com/fintelia/cargo-geiger --branch fix-479
$ cargo geiger
...
thread 'main' panicked at 'assertion failed: self.pending_ids.insert(id)', ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-0.73.1/src/cargo/core/package.rs:715:9
```

**Comment by fintelia** [comment]
Weird. Does running `cargo clean && cargo geiger` help?

I just tested again with this command and it worked for me:
```rust
cargo +stable install cargo-geiger --force --locked --git https://github.com/fintelia/cargo-geiger --branch fix-479
```

```
$ cargo +stable --version --verbose
cargo 1.72.0 (103a7ff2e 2023-08-15)
release: 1.72.0
commit-hash: 103a7ff2ee7678d34f34d778614c5eb2525ae9de
commit-date: 2023-08-15
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Debian n/a (trixie) [64-bit]
```

**Comment by klimburg** [comment]
Hmm nope both on my m1 mac and an ubuntu machine got same results

```
$ cargo +stable --version --verbose
cargo 1.72.1 (103a7ff2e 2023-08-15)
release: 1.72.1
commit-hash: 103a7ff2ee7678d34f34d778614c5eb2525ae9de
commit-date: 2023-08-15
host: x86_64-unknown-linux-gnu
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.1.2-DEV (sys:0.4.63+curl-8.1.2 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Ubuntu 20.04 (focal) [64-bit]

$ RUST_BACKTRACE=1 cargo +stable geiger
...
thread 'main' panicked at 'assertion failed: self.pending_ids.insert(id)', /home/kevin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-0.73.1/src/cargo/core/package.rs:715:9                                                                
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:117:5
   3: cargo::core::package::Downloads::start
   4: cargo::core::package::PackageSet::get_many
   5: cargo::ops::cargo_clean::clean
   6: cargo_geiger::scan::rs_file::resolve_rs_file_deps
   7: cargo_geiger::scan::default::scan
   8: cargo_geiger::scan::default::table::scan_to_table
   9: cargo_geiger::scan::default::scan_unsafe
  10: cargo_geiger::scan::scan
  11: cargo_geiger::main
  ```

**Comment by tmpfs** [comment]
FWIW, this fixed it for me on an M1 Mac using:

```
cargo +stable install cargo-geiger --force --locked --git https://github.com/fintelia/cargo-geiger --branch fix-479
```

**Comment by pinkforest** [comment]
The issue here is that `--locked` is not used and the .lock brings a problematic dependency that doesn't work across all cargo runtimes - see: https://github.com/geiger-rs/cargo-geiger/issues/479#issuecomment-1851955509

README has been changed to instruct people to use `--locked`

Superceded by #486

**Pull request closed without merging**
